### ISSUE TITLE
Two lines prompt

### ISSUE THREAD

**Issue by SpotHound** [vaaaaanquish/xontrib-powerline2#12]
Hello there!

Is there any way to set up multi-line prompt? 

Something like this (in zsh)

![image](https://user-images.githubusercontent.com/15269938/100270217-0310eb00-2f58-11eb-8ab8-75cd4cd34669.png)

If not, I think it may be interesting to add this feature, I could open a PR : )

Best regards.

**Comment by aalouaoui** [comment]
I also hope we can get that

**Comment by vaaaaanquish** [comment]
Thanks. I see.
Put PR or wait :)

**Comment by vaaaaanquish** [comment]
@SpotHound @aalouaoui 
Sorry for the delay, but you should see it using v1.3.0!
